
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'Missl'
version: '1.0.0'
config-version: 2

vars:
    project: missl
    project_dataset: noted-computing-279322.halo_1_1_test
    
    ga_age: noted-computing-279322.MissL1.halo_ga1_216655333_age
    fOrders: noted-computing-279322.halo_1_1.fOrders
    Calendar: noted-computing-279322.halo_1_1.Calendar
    magento_affiliate_marketing: noted-computing-279322.halo_1_1.magento_affiliate_marketing
    B_magento_Image4: noted-computing-279322.halo_1_1.fProductImage
    city_name: noted-computing-279322.city_corrected_name.City_Name
    magento_address: noted-computing-279322.MissL1.magento3_missl_live_sales_order_address
    magento_transactionnew: noted-computing-279322.MissL1.magento2_missl_live_sales_order
    B_zendesk_users: noted-computing-279322.MissL1.zendesk_Users
    zendesk_users: noted-computing-279322.halo_1_1.zendesk_users
    fAdInsights: noted-computing-279322.halo_1_1.fAdInsights
    fGABaseCosts: noted-computing-279322.halo_1_1.fGABaseCosts
    refKeywords: noted-computing-279322.halo_1_1.refKeywords
    fFBBaseTable: noted-computing-279322.halo_1_1.fFBBaseTable
    fb_array: noted-computing-279322.MissL1.halo_fb_380276816001252_adinsights
    ga_costs: noted-computing-279322.MissL1.halo_ga1_216655333_cost
    ga_transactions: noted-computing-279322.MissL1.missl_saudi_transactions_216655333_transactions
    ga_shopping_stages: noted-computing-279322.MissL1.halo_ga1_216655333_shoppingstages
    ga_skus: noted-computing-279322.MissL1.halo_ga1_216655333_sku
    ga_visitors: noted-computing-279322.MissL1.halo_ga1_216655333_users
    ga_landingpages: noted-computing-279322.MissL1.halo_ga1_216655333_landingpage
    ga_pages: noted-computing-279322.MissL1.halo_ga1_216655333_page
    ga_events: noted-computing-279322.MissL1.halo_ga1_216655333_events
    ga_searchterms: noted-computing-279322.MissL1.halo_ga1_216655333_searchterm
    ga_DeviceBrowsers: noted-computing-279322.MissL1.halo_ga1_216655333_device_browser
    ga_Banners: noted-computing-279322.MissL1.halo_ga1_216655333_banner
    ga_gender: noted-computing-279322.MissL1.halo_ga1_216655333_gender
    ga_age: noted-computing-279322.MissL1.halo_ga1_216655333_age
    ga_daylevelusers: noted-computing-279322.MissL1.halo_ga1_216655333_daylevelusers
    ga_sourcemediumnewusers: noted-computing-279322.MissL1.halo_ga1_216655333_sourcemediumnewusers
    ga_campaigncost: noted-computing-279322.MissL1.halo_ga1_216655333_campaign_cost
    ga_categoryskus: noted-computing-279322.MissL1.halo_ga1_216655333_category_product1
    B_magento_transaction: noted-computing-279322.MissL1.magento2_missl_live_sales_order
    B_magento_transactionnew: noted-computing-279322.MissL1.magento2_missl_live_sales_order
    B_magento_transaction_details: noted-computing-279322.MissL1.magento2_missl_live_sales_order_item
    B_magento_payment: noted-computing-279322.MissL1.magento2_missl_live_sales_order_payment
    B_magento_orderhist: noted-computing-279322.MissL1.magento2_missl_live_sales_order_status_history
    B_magento_address: noted-computing-279322.MissL1.magento3_missl_live_sales_order_address
    B_magento_tbluserinfo: noted-computing-279322.MissL1.magento2_missl_live_customer_entity
    B_magento_productentityvarchar: noted-computing-279322.MissL1.magento2_missl_live_catalog_product_entity_varchar
    B_magento_productentityint: noted-computing-279322.MissL1.magento2_missl_live_catalog_product_entity_int
    B_magento_productentitydec: noted-computing-279322.MissL1.magento2_missl_live_catalog_product_entity_decimal
    B_magento_productentity: noted-computing-279322.MissL1.magento2_missl_live_catalog_product_entity
    B_magento_productentitytext: noted-computing-279322.MissL1.magento2_missl_live_catalog_product_entity_text
    B_magento_producteav: noted-computing-279322.MissL1.magento2_missl_live_eav_attribute
    B_magento_producteavoption: noted-computing-279322.MissL1.magento2_missl_live_eav_attribute_option
    B_magento_producteavoptionvalue: noted-computing-279322.MissL1.magento2_missl_live_eav_attribute_option_value
    B_magento_productrelation: noted-computing-279322.MissL1.magento2_missl_live_catalog_product_relation
    B_magento_productinventoryrelation: noted-computing-279322.MissL1.magento2_missl_live_cataloginventory_stock_item
    magento_inventory: noted-computing-279322.halo_1_1.magento_productinventoryrelation
    B_magento_productcategoryentityvarchar: noted-computing-279322.MissL1.magento2_missl_live_catalog_category_entity_varchar
    B_magento_productcategoryproduct: noted-computing-279322.MissL1.magento2_missl_live_catalog_category_product
    B_magento_productcategoryentity: noted-computing-279322.MissL1.magento2_missl_live_catalog_category_entity
    B_magento_Image1: noted-computing-279322.MissL1.magento2_missl_live_core_config_data
    B_magento_Image4: noted-computing-279322.halo_1_1.fProductImage
    B_magento_Image2: noted-computing-279322.MissL1.magento2_missl_live_catalog_product_entity_media_gallery
    B_magento_Image3: noted-computing-279322.MissL1.magento2_missl_live_catalog_product_entity_media_gallery_value
    B_magento_categoryproductindex: noted-computing-279322.MissL1.magento2_missl_live_catalog_category_product_index
    B_magento_salesrule_coupon: noted-computing-279322.MissL1.magento2_missl_live_salesrule_coupon
    B_magento_salesrule_coupon_usage: noted-computing-279322.MissL1.magento2_missl_live_salesrule_coupon_usage
    B_magento_product_index_price: noted-computing-279322.MissL1.magento2_missl_live_catalog_product_index_price
    B_magento_customeraddress: noted-computing-279322.MissL1.magento_misslsaras_customer_address_entity
    B_magento_ordersgrid: noted-computing-279322.MissL1.magento2_missl_live_sales_order_grid
    B_magento_influencerscode: noted-computing-279322.influencer_codes.Influencer_Codes
    B_magento_facebookflatfile_eg: noted-computing-279322.MissL1.facebook_ads_380276816001252_adinsights_breakdown_publisher_platform
    B_magento_facebookflatfile_ksa: noted-computing-279322.MissL1.Halo_ksa_fb_421543735473067_adinsights_breakdown_publisher_platform
    fbnew_adinsights_eg: noted-computing-279322.MissL1.halo_fb_380276816001252_adinsights
    fbnew_adinsights_ksa: noted-computing-279322.MissL1.Halo_ksa_fb_421543735473067_adinsights
    B_magento_snapchatflatfile: noted-computing-279322.snapchat_data_missl.Snapchat_stitch
    B_magento_channelgroupksa: noted-computing-279322.halo_1_1.channel_ksa
    B_magento_historicorders: noted-computing-279322.halo_1_1.historic_orders
    B_magento_target: noted-computing-279322.halo_1_1.magento_target
    B_magento_productstatic: noted-computing-279322.MissL1.magento3_missl_live_catalog_category_product_static
    B_magento_marketingtarget: noted-computing-279322.halo_1_1.magento_sales_target
    B_magento_marketingchanneltarget: noted-computing-279322.marketing_goals_trial.Marketing_trial
    B_magento_aramex: noted-computing-279322.halo_1_1.aramex
    B_zendesk_tickets: noted-computing-279322.MissL1.zendesk_Tickets
    B_zendesk_ticketmetrics: noted-computing-279322.MissL1.zendesk_TicketMetrics
    B_zendesk_users: noted-computing-279322.MissL1.zendesk_Users
    B_magento_affiliate_marketing: noted-computing-279322.affiliate_codes_1.Affiliate_Marketing_Codes
    B_youtubeflatfile: noted-computing-279322.halo_1_1.youtube
    B_tiktok_ksa_flatfile: noted-computing-279322.tiktok_ksa.tiktok_ksa
    B_Revenue_Goals: noted-computing-279322.sales_targets.Revenue_Goals_KSA_Day_level
    Product_entity: noted-computing-279322.halo_1_1.magento_productentity
    city_name: noted-computing-279322.city_corrected_name.City_Name

    Country: ('MissL')

# This setting configures which "profile" dbt uses for this project.
profile: 'misslksa'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  Missl:
  #give the project name used on the top
    Missl_KSA:
      +full_refresh: true
        # Applies to all files under models/example/
      Tables:
          materialized: table
      Views:
          materialized: view
          